### ISSUE TITLE
.webhook_secret_keys  translation not working

### ISSUE THREAD

**Issue by xchopin** [FLUX-SE/SyliusPayumStripePlugin#19]
Hi,

I've just installed this plugin however it seems like your translation key flux_se_sylius_payum_stripe_plugin.form.gateway_configuration.stripe.webhook_secret_keys

doesn't have a value? 

![image](https://user-images.githubusercontent.com/15248061/112047775-f8551400-8b4d-11eb-942a-0a81a7d572b6.png)

but when I check the translation file in your repository it seems filled :(

**Comment by Prometee** [comment]
Hi @xchopin,

This can't append because some Behat tests needs the translated value to exist, I also double check it into a production and on the test application.

Typically, this can append when your cache is not totally cleared or there is some apcu/opcache not fully cleared.
Try to manually remove your `var/cache/dev` or `var/cache/prod` folder and ultimately restart your php-fpm instance (if it come from opcache a restart will flush it).
