### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by xchopin** [FLUX-SE/SyliusPayumStripePlugin#23]
Hi,

I have seen you made a bunch of commits with interesting features since the last version (thank you for that!) 

Is it possible to get a 1.3.* version? :) 

Thanks!

**Comment by Prometee** [comment]
@xchopin Thank you very much 😃

I hope to release it this week, I need to finish writing and enhance the BEHAT tests.
But in the meantime you can already test the `dev-master` version, I made tests with my own stripe test account : the refund and authorize are working fine. The only thing I didn't tested yet is the ability to cancel an authorized payment, because Sylius don't have an UI button allowing to cancel the payment (it's possible to cancel the order but not a payment).

**Comment by xchopin** [comment]
okay thank you!
