### ISSUE TITLE
Declined payment cannot be retried

### ISSUE THREAD

**Issue by JoppeDC** [FLUX-SE/SyliusPayumStripePlugin#46]
When you "fail" a payment in stripe, you get redirect to the stripe interface again to select another method.
If you close the screen on this window, obviously the payment is never paid.

If you then try to pay the outstanding order via the Sylius UI (Via user profile -> Orders -> and you can pay unpaid order), you get the following error message.

```
FluxSE\PayumStripe\Action\StatusSessionAction::isCaptureStatus():
Argument #2 ($paymentStatus) must be of type string, null given,
called in vendor/flux-se/payum-stripe/src/Action/StatusSessionAction.php on line 28
```

I've already done some minor investigating, and this only happens when the payment was previously failed or declined.
The last_error_message of the request is `payment_method_customer_decline`, and the request doesn't contain a lot of data.

This appears to be a bug, either in the sylius integration, or the payumStripe bundle.

**Comment by Prometee** [comment]
Hello @JoppeDC !

Normally when you are on the Stripe Checkout portal, you stay on it, to retry another payment method. Then when you come back from the portal and you don't have pay yet, Sylius is displaying the payment method choices. If you select Stripe Checkout for the second time, the previous CheckoutSession is expired and a new one is created.

If the expiration is not done, that's probably because the plugin you are running it's a previous version.
Can you check the versions of the plugin, the payum stripe bundle and the payum stripe lib you are using ?

Also according to the error message you are reporting, a Stripe Checkout Session should not been checked at this point, instead the underlying Stripe `PaymentIntent` should be checked. So that's mean something happened during the creation of the Stripe Checkout Session, do you have the full stack trace of this error ?
